### PR TITLE
fix(cli): shell-escape auth login exports

### LINKED ISSUE #1110: [Bug]: Escape `ugoite auth login` token exports before recommending eval
## Issue Type
bug

## Phase
release-preparation

## Version
0.1.0-dev (main branch snapshot)

## Description
`ugoite auth login` prints `export UGOITE_AUTH_BEARER_TOKEN={token}` without shell escaping, then immediately recommends `eval "$(ugoite auth login ...)"`.

Because the token value is interpolated directly into shell syntax, any shell metacharacters inside the token become executable code in the user's shell. That makes the documented happy path unsafe when a backend returns a malicious or malformed token.

Relevant code:
- `ugoite-cli/src/commands/auth.rs:95-104`
- the current output is `println!("export UGOITE_AUTH_BEARER_TOKEN={token}");`

## Steps to Reproduce
1. Inspect `ugoite-cli/src/commands/auth.rs` around the `AuthSubCmd::Login` success path.
2. Observe that the CLI prints an unquoted `export` line and recommends `eval "$(ugoite auth login ...)"`.
3. Replace `token` conceptually with a shell-significant value such as `$(touch /tmp/ugoite-pwned)`.
4. Run the same pattern manually in a shell:
   ```bash
   token='$(touch /tmp/ugoite-pwned)'
   eval "$(printf 'export UGOITE_AUTH_BEARER_TOKEN=%s
' "$token")"
   ```
5. Confirm the shell executes the embedded command instead of treating the token as opaque data.

## Expected Behavior
The CLI should shell-escape token values before printing export commands, or stop recommending `eval` entirely and emit a safer machine-readable format.

At minimum:
- escape the token for POSIX shells before printing `export ...`
- keep the docs/example aligned with the escaped output
- add a regression test covering tokens with shell metacharacters

## Environment
- Repository audit on Linux workspace
- Verified in `ugoite-cli/src/commands/auth.rs:95-104`

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- shell-escape the exported `UGOITE_AUTH_BEARER_TOKEN` value from `ugoite auth login`
- clarify in CLI help and runtime guidance that the printed export is POSIX-shell-safe
- update the release quickstart consumer and add REQ-OPS-015 regression coverage for metacharacter-bearing and empty bearer tokens

## Related Issue (required)
closes #1110

## Testing
- [x] `cd ugoite-cli && cargo fmt --check`
- [x] `cd ugoite-cli && cargo clippy --no-default-features -- -D warnings`
- [x] `cd ugoite-cli && cargo llvm-cov --summary-only --fail-under-lines 100 --no-default-features --jobs 1` (with CI-aligned env)
- [x] `cd /workspace && mise run test` (with low-memory env and linker wrapper used in this environment)

### CODE REVIEW

File: ugoite-cli/src/commands/auth.rs [hunk 1]
```diff
@@ -98,9 +98,10 @@ pub async fn run(cmd: AuthCmd) -> Result<()> {
                 } else {
                     " --username USER --totp-code CODE"
                 };
-                println!("export UGOITE_AUTH_BEARER_TOKEN={token}");
+                let quoted_token = posix_shell_quote(token);
```
Comment (tohboeh5) [inline ugoite-cli/src/commands/auth.rs]: Changing the exported token to a shell-quoted literal breaks existing consumers that strip the `export UGOITE_AUTH_BEARER_TOKEN=` prefix instead of `eval`-ing the line. The repo already has one such consumer in `scripts/verify-release-container-quickstart.sh:214`, and the current CI failure shows the effect: it stores the surrounding quotes in `UGOITE_AUTH_BEARER_TOKEN`, then the next `space list` call goes out with an invalid bearer token and gets `401 Unauthorized`. Could we either keep a machine-readable/raw output contract for non-shell consumers, or update all in-repo consumers before changing this line?

**Comment by tohboeh5** [comment]
Overview:

The shell-escaping direction is good and the targeted CLI auth test slice passed locally (`cd ugoite-cli && cargo test --no-default-features --test test_auth auth_login -- --nocapture`). I left one blocking comment on the changed export line, though: the PR changes the output contract in a way that breaks an existing in-repo consumer.

`verify-release-container-quickstart.sh` currently strips the `export UGOITE_AUTH_BEARER_TOKEN=` prefix and re-exports the remainder as a raw value. With the new quoted output, that script stores the surrounding quotes in the environment variable, and the release quickstart job now fails with `401 Unauthorized` on the next authenticated CLI call. So the escaping change itself is sensible, but the consumer contract needs to be updated in lockstep before this is safe to merge.
