### PR TITLE
fix: keep admin-space separate in newcomer flows

### LINKED ISSUE #1025: [Bug]: Newcomer login exposes reserved admin-space as a normal first workspace
## Issue Type
bug

## Phase
implementation

## Version
main (observed on 2026-03-29)

## Description
After the first login, the spaces list exposes `admin-space` like a normal workspace and can place it ahead of `default`.

That makes the newcomer path confusing and risks dropping a brand-new user into an internal/admin-oriented space before they understand the product model.

Affected areas:
- `backend/src/app/main.py`
- `backend/src/app/api/endpoints/space.py`
- `frontend/src/routes/spaces/index.tsx`
- `docker-compose.release.yaml`
- `docs/guide/container-quickstart.md`

## Steps to Reproduce
1. Start the release-style local stack with Mock OAuth.
2. Sign in and open `/spaces`.
3. Observe that `admin-space` is listed as a normal workspace.
4. Use the first visible `Open Space` action.
5. Observe that the first landing target can be `admin-space` instead of the newcomer-friendly default space described in the docs.

## Expected Behavior
Newcomer-facing flows should hide reserved/admin spaces by default or clearly separate them from normal user workspaces so the first post-login path lands in a safe, user-facing default space.

## Environment
Reproduced locally on 2026-03-29 against the repository `main` branch using the release-style frontend/backend flow with Mock OAuth.

### PR DESCRIPTION
**Pull request by tohboeh5**
## Summary
- mark reserved admin-space explicitly in the spaces API, keep `default` first, and separate admin spaces from the primary newcomer list
- avoid auto-selecting reserved admin-space in the frontend fallback selection flow and add REQ-linked coverage for ordering, empty-state, and blank-name sorting
- document the release/mock-oauth newcomer path and verify it with the Playwright smoke flow plus the full repo test suite

## Related Issue (required)
closes #1025

## Testing
- [x] `cd frontend && npm run test:run -- src/lib/client.test.ts src/lib/space-store.test.ts src/routes/spaces/index.test.tsx`
- [x] `bash e2e/scripts/run-e2e.sh smoke`
- [x] `TMPDIR=/workspace/tmp TMP=/workspace/tmp TEMP=/workspace/tmp mise run test`

### CODE REVIEW

File: frontend/src/lib/space-store.ts [hunk 1]
```diff
@@ -43,34 +42,35 @@ export function createSpaceStore() {
...
 		try {
-			const fetchedSpaces = await spaceApi.list();
+			const fetchedSpaces = sortSpaces(await spaceApi.list());
 			setSpaces(fetchedSpaces);
+			const selectableSpaces = fetchedSpaces.filter((space) => !isReservedAdminSpace(space));
 
 			// Try to restore persisted space selection
 			const persistedId = getPersistedSpaceId();
-			if (persistedId && fetchedSpaces.some((space) => space.id === persistedId)) {
+			if (persistedId && selectableSpaces.some((space) => space.id === persistedId)) {
```
Comment (tohboeh5) [inline frontend/src/lib/space-store.ts]: We now ignore a persisted `admin-space` selection here, but we never repair it in portable/local preferences. That means the invalid `selected_space_id` survives every reload, and any other surface that reads preferences directly still sees `admin-space` as the users chosen space. Can we persist the corrected selection (or clear the stale one) when we hit this branch instead of only fixing it in memory?
